# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/MDLP',
                'doc_host': 'https://fevzikilas.github.io',
                'git_url': 'https://github.com/fevzikilas/MDLP',
                'lib_path': 'MDLP'},
  'syms': {'MDLP.core': {'MDLP.core.foo': ('core.html#foo', 'MDLP/core.py')}}}
